const voices = {
  "af-ZA": {"Adri": "af-ZA-AdriNeural", "Willem": "af-ZA-WillemNeural"},
  "am-ET": {"Mekdes": "am-ET-MekdesNeural", "Ameha": "am-ET-AmehaNeural"},
  "ar-AE": {"Fatima": "ar-AE-FatimaNeural", "Hamdan": "ar-AE-HamdanNeural"},
  "ar-BH": {"Laila": "ar-BH-LailaNeural", "Ali": "ar-BH-AliNeural"},
  "ar-DZ": {"Amina": "ar-DZ-AminaNeural", "Ismael": "ar-DZ-IsmaelNeural"},
  "ar-EG": {"Salma": "ar-EG-SalmaNeural", "Shakir": "ar-EG-ShakirNeural"},
  "ar-IQ": {"Rana": "ar-IQ-RanaNeural", "Bassel": "ar-IQ-BasselNeural"},
  "ar-JO": {"Sana": "ar-JO-SanaNeural", "Taim": "ar-JO-TaimNeural"},
  "ar-KW": {"Noura": "ar-KW-NouraNeural", "Fahed": "ar-KW-FahedNeural"},
  "ar-LB": {"Layla": "ar-LB-LaylaNeural", "Rami": "ar-LB-RamiNeural"},
  "ar-LY": {"Iman": "ar-LY-ImanNeural", "Omar": "ar-LY-OmarNeural"},
  "ar-MA": {"Mouna": "ar-MA-MounaNeural", "Jamal": "ar-MA-JamalNeural"},
  "ar-OM": {"Aysha": "ar-OM-AyshaNeural", "Abdullah": "ar-OM-AbdullahNeural"},
  "ar-QA": {"Amal": "ar-QA-AmalNeural", "Moaz": "ar-QA-MoazNeural"},
  "ar-SA": {"Zariyah": "ar-SA-ZariyahNeural", "Hamed": "ar-SA-HamedNeural"},
  "ar-SY": {"Amany": "ar-SY-AmanyNeural", "Laith": "ar-SY-LaithNeural"},
  "ar-TN": {"Reem": "ar-TN-ReemNeural", "Hedi": "ar-TN-HediNeural"},
  "ar-YE": {"Maryam": "ar-YE-MaryamNeural", "Saleh": "ar-YE-SalehNeural"},
  "as-IN": {"Yashica": "as-IN-YashicaNeural", "Priyom": "as-IN-PriyomNeural"},
  "az-AZ": {"Banu": "az-AZ-BanuNeural", "Babek": "az-AZ-BabekNeural"},
  "bg-BG": {"Kalina": "bg-BG-KalinaNeural", "Borislav": "bg-BG-BorislavNeural"},
  "bn-BD": {
    "Nabanita": "bn-BD-NabanitaNeural",
    "Pradeep": "bn-BD-PradeepNeural"
  },
  "bn-IN": {
    "Tanishaa": "bn-IN-TanishaaNeural",
    "Bashkar": "bn-IN-BashkarNeural"
  },
  "bs-BA": {"Vesna": "bs-BA-VesnaNeural", "Goran": "bs-BA-GoranNeural"},
  "ca-ES": {
    "Joana": "ca-ES-JoanaNeural",
    "Enric": "ca-ES-EnricNeural",
    "Alba": "ca-ES-AlbaNeural"
  },
  "cs-CZ": {"Vlasta": "cs-CZ-VlastaNeural", "Antonin": "cs-CZ-AntoninNeural"},
  "cy-GB": {"Nia": "cy-GB-NiaNeural", "Aled": "cy-GB-AledNeural"},
  "da-DK": {"Christel": "da-DK-ChristelNeural", "Jeppe": "da-DK-JeppeNeural"},
  "de-AT": {"Ingrid": "de-AT-IngridNeural", "Jonas": "de-AT-JonasNeural"},
  "de-CH": {"Leni": "de-CH-LeniNeural", "Jan": "de-CH-JanNeural"},
  "de-DE": {
    "Katja": "de-DE-KatjaNeural",
    "Conrad": "de-DE-ConradNeural",
    "SeraphinaMultilingual": "de-DE-SeraphinaMultilingualNeural",
    "FlorianMultilingual": "de-DE-FlorianMultilingualNeural",
    "Amala": "de-DE-AmalaNeural",
    "Bernd": "de-DE-BerndNeural",
    "Christoph": "de-DE-ChristophNeural",
    "Elke": "de-DE-ElkeNeural",
    "Gisela": "de-DE-GiselaNeural",
    "Kasper": "de-DE-KasperNeural",
    "Killian": "de-DE-KillianNeural",
    "Klarissa": "de-DE-KlarissaNeural",
    "Klaus": "de-DE-KlausNeural",
    "Louisa": "de-DE-LouisaNeural",
    "Maja": "de-DE-MajaNeural",
    "Ralf": "de-DE-RalfNeural",
    "Tanja": "de-DE-TanjaNeural",
    "Florian:DragonHD": "de-DE-Florian:DragonHDLatestNeural",
    "Seraphina:DragonHD": "de-DE-Seraphina:DragonHDLatestNeural"
  },
  "el-GR": {"Athina": "el-GR-AthinaNeural", "Nestoras": "el-GR-NestorasNeural"},
  "en-AU": {
    "Natasha": "en-AU-NatashaNeural",
    "William": "en-AU-WilliamNeural",
    "Annette": "en-AU-AnnetteNeural",
    "Carly": "en-AU-CarlyNeural",
    "Darren": "en-AU-DarrenNeural",
    "Duncan": "en-AU-DuncanNeural",
    "Elsie": "en-AU-ElsieNeural",
    "Freya": "en-AU-FreyaNeural",
    "Joanne": "en-AU-JoanneNeural",
    "Ken": "en-AU-KenNeural",
    "Kim": "en-AU-KimNeural",
    "Neil": "en-AU-NeilNeural",
    "Tim": "en-AU-TimNeural",
    "Tina": "en-AU-TinaNeural",
    "WilliamMultilingual": "en-AU-WilliamMultilingualNeural"
  },
  "en-CA": {"Clara": "en-CA-ClaraNeural", "Liam": "en-CA-LiamNeural"},
  "en-GB": {
    "Sonia": "en-GB-SoniaNeural",
    "Ryan": "en-GB-RyanNeural",
    "Libby": "en-GB-LibbyNeural",
    "AdaMultilingual": "en-GB-AdaMultilingualNeural",
    "OllieMultilingual": "en-GB-OllieMultilingualNeural",
    "Abbi": "en-GB-AbbiNeural",
    "Alfie": "en-GB-AlfieNeural",
    "Bella": "en-GB-BellaNeural",
    "Elliot": "en-GB-ElliotNeural",
    "Ethan": "en-GB-EthanNeural",
    "Hollie": "en-GB-HollieNeural",
    "Maisie": "en-GB-MaisieNeural",
    "Noah": "en-GB-NoahNeural",
    "Oliver": "en-GB-OliverNeural",
    "Olivia": "en-GB-OliviaNeural",
    "Thomas": "en-GB-ThomasNeural"
  },
  "en-HK": {"Yan": "en-HK-YanNeural", "Sam": "en-HK-SamNeural"},
  "en-IE": {"Emily": "en-IE-EmilyNeural", "Connor": "en-IE-ConnorNeural"},
  "en-IN": {
    "Aarav": "en-IN-AaravNeural",
    "Aashi": "en-IN-AashiNeural",
    "Aarti": "en-IN-AartiNeural",
    "Arjun": "en-IN-ArjunNeural",
    "Ananya": "en-IN-AnanyaNeural",
    "Kavya": "en-IN-KavyaNeural",
    "Kunal": "en-IN-KunalNeural",
    "Neerja": "en-IN-NeerjaNeural",
    "Prabhat": "en-IN-PrabhatNeural",
    "Rehaan": "en-IN-RehaanNeural",
    "AartiIndic": "en-IN-AartiIndicNeural",
    "ArjunIndic": "en-IN-ArjunIndicNeural",
    "NeerjaIndic": "en-IN-NeerjaIndicNeural",
    "PrabhatIndic": "en-IN-PrabhatIndicNeural"
  },
  "en-KE": {"Asilia": "en-KE-AsiliaNeural", "Chilemba": "en-KE-ChilembaNeural"},
  "en-NG": {"Ezinne": "en-NG-EzinneNeural", "Abeo": "en-NG-AbeoNeural"},
  "en-NZ": {"Molly": "en-NZ-MollyNeural", "Mitchell": "en-NZ-MitchellNeural"},
  "en-PH": {"Rosa": "en-PH-RosaNeural", "James": "en-PH-JamesNeural"},
  "en-SG": {"Luna": "en-SG-LunaNeural", "Wayne": "en-SG-WayneNeural"},
  "en-TZ": {"Imani": "en-TZ-ImaniNeural", "Elimu": "en-TZ-ElimuNeural"},
  "en-US": {
    "AvaMultilingual": "en-US-AvaMultilingualNeural",
    "AndrewMultilingual": "en-US-AndrewMultilingualNeural",
    "EmmaMultilingual": "en-US-EmmaMultilingualNeural",
    "AlloyTurboMultilingual": "en-US-AlloyTurboMultilingualNeural",
    "EchoTurboMultilingual": "en-US-EchoTurboMultilingualNeural",
    "FableTurboMultilingual": "en-US-FableTurboMultilingualNeural",
    "OnyxTurboMultilingual": "en-US-OnyxTurboMultilingualNeural",
    "NovaTurboMultilingual": "en-US-NovaTurboMultilingualNeural",
    "ShimmerTurboMultilingual": "en-US-ShimmerTurboMultilingualNeural",
    "BrianMultilingual": "en-US-BrianMultilingualNeural",
    "Ava": "en-US-AvaNeural",
    "Andrew": "en-US-AndrewNeural",
    "Emma": "en-US-EmmaNeural",
    "Brian": "en-US-BrianNeural",
    "Jenny": "en-US-JennyNeural",
    "Guy": "en-US-GuyNeural",
    "Aria": "en-US-AriaNeural",
    "Davis": "en-US-DavisNeural",
    "Jane": "en-US-JaneNeural",
    "Jason": "en-US-JasonNeural",
    "Kai": "en-US-KaiNeural",
    "Luna": "en-US-LunaNeural",
    "Sara": "en-US-SaraNeural",
    "Tony": "en-US-TonyNeural",
    "Nancy": "en-US-NancyNeural",
    "CoraMultilingual": "en-US-CoraMultilingualNeural",
    "ChristopherMultilingual": "en-US-ChristopherMultilingualNeural",
    "BrandonMultilingual": "en-US-BrandonMultilingualNeural",
    "Amber": "en-US-AmberNeural",
    "Ana": "en-US-AnaNeural",
    "Ashley": "en-US-AshleyNeural",
    "Brandon": "en-US-BrandonNeural",
    "Christopher": "en-US-ChristopherNeural",
    "Cora": "en-US-CoraNeural",
    "Elizabeth": "en-US-ElizabethNeural",
    "Eric": "en-US-EricNeural",
    "Jacob": "en-US-JacobNeural",
    "JennyMultilingual": "en-US-JennyMultilingualNeural",
    "Michelle": "en-US-MichelleNeural",
    "Monica": "en-US-MonicaNeural",
    "Roger": "en-US-RogerNeural",
    "RyanMultilingual": "en-US-RyanMultilingualNeural",
    "Steffan": "en-US-SteffanNeural",
    "AdamMultilingual": "en-US-AdamMultilingualNeural",
    "AIGenerate1": "en-US-AIGenerate1Neural",
    "AIGenerate2": "en-US-AIGenerate2Neural",
    "AmandaMultilingual": "en-US-AmandaMultilingualNeural",
    "AshTurboMultilingual": "en-US-AshTurboMultilingualNeural",
    "Blue": "en-US-BlueNeural",
    "DavisMultilingual": "en-US-DavisMultilingualNeural",
    "DerekMultilingual": "en-US-DerekMultilingualNeural",
    "DustinMultilingual": "en-US-DustinMultilingualNeural",
    "EvelynMultilingual": "en-US-EvelynMultilingualNeural",
    "LewisMultilingual": "en-US-LewisMultilingualNeural",
    "LolaMultilingual": "en-US-LolaMultilingualNeural",
    "NancyMultilingual": "en-US-NancyMultilingualNeural",
    "PhoebeMultilingual": "en-US-PhoebeMultilingualNeural",
    "SamuelMultilingual": "en-US-SamuelMultilingualNeural",
    "SerenaMultilingual": "en-US-SerenaMultilingualNeural",
    "SteffanMultilingual": "en-US-SteffanMultilingualNeural",
    "Adam:DragonHD": "en-US-Adam:DragonHDLatestNeural",
    "Andrew:DragonHD": "en-US-Andrew:DragonHDLatestNeural",
    "Andrew2:DragonHD": "en-US-Andrew2:DragonHDLatestNeural",
    "Ava:DragonHD": "en-US-Ava:DragonHDLatestNeural",
    "Brian:DragonHD": "en-US-Brian:DragonHDLatestNeural",
    "Davis:DragonHD": "en-US-Davis:DragonHDLatestNeural",
    "Emma:DragonHD": "en-US-Emma:DragonHDLatestNeural",
    "Emma2:DragonHD": "en-US-Emma2:DragonHDLatestNeural",
    "Steffan:DragonHD": "en-US-Steffan:DragonHDLatestNeural",
    "Alloy:DragonHD": "en-US-Alloy:DragonHDLatestNeural",
    "Andrew3:DragonHD": "en-US-Andrew3:DragonHDLatestNeural",
    "Aria:DragonHD": "en-US-Aria:DragonHDLatestNeural",
    "Ava3:DragonHD": "en-US-Ava3:DragonHDLatestNeural",
    "Bree:DragonHD": "en-US-Bree:DragonHDLatestNeural",
    "Jenny:DragonHD": "en-US-Jenny:DragonHDLatestNeural",
    "Andrew_DragonHD": "en-US-MultiTalker-Ava-Andrew:DragonHDLatestNeural",
    "Steffan_DragonHD": "en-US-MultiTalker-Ava-Steffan:DragonHDLatestNeural",
    "Nova:DragonHD": "en-US-Nova:DragonHDLatestNeural",
    "Phoebe:DragonHD": "en-US-Phoebe:DragonHDLatestNeural",
    "Serena:DragonHD": "en-US-Serena:DragonHDLatestNeural"
  },
  "en-ZA": {"Leah": "en-ZA-LeahNeural", "Luke": "en-ZA-LukeNeural"},
  "es-AR": {"Elena": "es-AR-ElenaNeural", "Tomas": "es-AR-TomasNeural"},
  "es-BO": {"Sofia": "es-BO-SofiaNeural", "Marcelo": "es-BO-MarceloNeural"},
  "es-CL": {
    "Catalina": "es-CL-CatalinaNeural",
    "Lorenzo": "es-CL-LorenzoNeural"
  },
  "es-CO": {"Salome": "es-CO-SalomeNeural", "Gonzalo": "es-CO-GonzaloNeural"},
  "es-CR": {"Maria": "es-CR-MariaNeural", "Juan": "es-CR-JuanNeural"},
  "es-CU": {"Belkys": "es-CU-BelkysNeural", "Manuel": "es-CU-ManuelNeural"},
  "es-DO": {"Ramona": "es-DO-RamonaNeural", "Emilio": "es-DO-EmilioNeural"},
  "es-EC": {"Andrea": "es-EC-AndreaNeural", "Luis": "es-EC-LuisNeural"},
  "es-ES": {
    "Elvira": "es-ES-ElviraNeural",
    "Alvaro": "es-ES-AlvaroNeural",
    "ArabellaMultilingual": "es-ES-ArabellaMultilingualNeural",
    "IsidoraMultilingual": "es-ES-IsidoraMultilingualNeural",
    "TristanMultilingual": "es-ES-TristanMultilingualNeural",
    "XimenaMultilingual": "es-ES-XimenaMultilingualNeural",
    "Abril": "es-ES-AbrilNeural",
    "Arnau": "es-ES-ArnauNeural",
    "Dario": "es-ES-DarioNeural",
    "Elias": "es-ES-EliasNeural",
    "Estrella": "es-ES-EstrellaNeural",
    "Irene": "es-ES-IreneNeural",
    "Laia": "es-ES-LaiaNeural",
    "Lia": "es-ES-LiaNeural",
    "Nil": "es-ES-NilNeural",
    "Saul": "es-ES-SaulNeural",
    "Teo": "es-ES-TeoNeural",
    "Triana": "es-ES-TrianaNeural",
    "Vera": "es-ES-VeraNeural",
    "Ximena": "es-ES-XimenaNeural",
    "Tristan:DragonHD": "es-ES-Tristan:DragonHDLatestNeural",
    "Ximena:DragonHD": "es-ES-Ximena:DragonHDLatestNeural"
  },
  "es-GQ": {"Teresa": "es-GQ-TeresaNeural", "Javier": "es-GQ-JavierNeural"},
  "es-GT": {"Marta": "es-GT-MartaNeural", "Andres": "es-GT-AndresNeural"},
  "es-HN": {"Karla": "es-HN-KarlaNeural", "Carlos": "es-HN-CarlosNeural"},
  "es-MX": {
    "Dalia": "es-MX-DaliaNeural",
    "Jorge": "es-MX-JorgeNeural",
    "Beatriz": "es-MX-BeatrizNeural",
    "Candela": "es-MX-CandelaNeural",
    "Carlota": "es-MX-CarlotaNeural",
    "Cecilio": "es-MX-CecilioNeural",
    "Gerardo": "es-MX-GerardoNeural",
    "Larissa": "es-MX-LarissaNeural",
    "Liberto": "es-MX-LibertoNeural",
    "Luciano": "es-MX-LucianoNeural",
    "Marina": "es-MX-MarinaNeural",
    "Nuria": "es-MX-NuriaNeural",
    "Pelayo": "es-MX-PelayoNeural",
    "Renata": "es-MX-RenataNeural",
    "Yago": "es-MX-YagoNeural",
    "DaliaMultilingual": "es-MX-DaliaMultilingualNeural",
    "JorgeMultilingual": "es-MX-JorgeMultilingualNeural"
  },
  "es-NI": {
    "Yolanda": "es-NI-YolandaNeural",
    "Federico": "es-NI-FedericoNeural"
  },
  "es-PA": {
    "Margarita": "es-PA-MargaritaNeural",
    "Roberto": "es-PA-RobertoNeural"
  },
  "es-PE": {"Camila": "es-PE-CamilaNeural", "Alex": "es-PE-AlexNeural"},
  "es-PR": {"Karina": "es-PR-KarinaNeural", "Victor": "es-PR-VictorNeural"},
  "es-PY": {"Tania": "es-PY-TaniaNeural", "Mario": "es-PY-MarioNeural"},
  "es-SV": {"Lorena": "es-SV-LorenaNeural", "Rodrigo": "es-SV-RodrigoNeural"},
  "es-US": {"Paloma": "es-US-PalomaNeural", "Alonso": "es-US-AlonsoNeural"},
  "es-UY": {"Valentina": "es-UY-ValentinaNeural", "Mateo": "es-UY-MateoNeural"},
  "es-VE": {"Paola": "es-VE-PaolaNeural", "Sebastian": "es-VE-SebastianNeural"},
  "et-EE": {"Anu": "et-EE-AnuNeural", "Kert": "et-EE-KertNeural"},
  "eu-ES": {"Ainhoa": "eu-ES-AinhoaNeural", "Ander": "eu-ES-AnderNeural"},
  "fa-IR": {"Dilara": "fa-IR-DilaraNeural", "Farid": "fa-IR-FaridNeural"},
  "fi-FI": {
    "Selma": "fi-FI-SelmaNeural",
    "Harri": "fi-FI-HarriNeural",
    "Noora": "fi-FI-NooraNeural"
  },
  "fil-PH": {
    "Blessica": "fil-PH-BlessicaNeural",
    "Angelo": "fil-PH-AngeloNeural"
  },
  "fr-BE": {"Charline": "fr-BE-CharlineNeural", "Gerard": "fr-BE-GerardNeural"},
  "fr-CA": {
    "Sylvie": "fr-CA-SylvieNeural",
    "Jean": "fr-CA-JeanNeural",
    "Antoine": "fr-CA-AntoineNeural",
    "Thierry": "fr-CA-ThierryNeural"
  },
  "fr-CH": {"Ariane": "fr-CH-ArianeNeural", "Fabrice": "fr-CH-FabriceNeural"},
  "fr-FR": {
    "Denise": "fr-FR-DeniseNeural",
    "Henri": "fr-FR-HenriNeural",
    "VivienneMultilingual": "fr-FR-VivienneMultilingualNeural",
    "RemyMultilingual": "fr-FR-RemyMultilingualNeural",
    "LucienMultilingual": "fr-FR-LucienMultilingualNeural",
    "Alain": "fr-FR-AlainNeural",
    "Brigitte": "fr-FR-BrigitteNeural",
    "Celeste": "fr-FR-CelesteNeural",
    "Claude": "fr-FR-ClaudeNeural",
    "Coralie": "fr-FR-CoralieNeural",
    "Eloise": "fr-FR-EloiseNeural",
    "Jacqueline": "fr-FR-JacquelineNeural",
    "Jerome": "fr-FR-JeromeNeural",
    "Josephine": "fr-FR-JosephineNeural",
    "Maurice": "fr-FR-MauriceNeural",
    "Yves": "fr-FR-YvesNeural",
    "Yvette": "fr-FR-YvetteNeural",
    "Remy:DragonHD": "fr-FR-Remy:DragonHDLatestNeural",
    "Vivienne:DragonHD": "fr-FR-Vivienne:DragonHDLatestNeural"
  },
  "ga-IE": {"Orla": "ga-IE-OrlaNeural", "Colm": "ga-IE-ColmNeural"},
  "gl-ES": {"Sabela": "gl-ES-SabelaNeural", "Roi": "gl-ES-RoiNeural"},
  "gu-IN": {"Dhwani": "gu-IN-DhwaniNeural", "Niranjan": "gu-IN-NiranjanNeural"},
  "he-IL": {"Hila": "he-IL-HilaNeural", "Avri": "he-IL-AvriNeural"},
  "hi-IN": {
    "Aarav": "hi-IN-AaravNeural",
    "Ananya": "hi-IN-AnanyaNeural",
    "Aarti": "hi-IN-AartiNeural",
    "Arjun": "hi-IN-ArjunNeural",
    "Kavya": "hi-IN-KavyaNeural",
    "Kunal": "hi-IN-KunalNeural",
    "Rehaan": "hi-IN-RehaanNeural",
    "Swara": "hi-IN-SwaraNeural",
    "Madhur": "hi-IN-MadhurNeural"
  },
  "hr-HR": {
    "Gabrijela": "hr-HR-GabrijelaNeural",
    "Srecko": "hr-HR-SreckoNeural"
  },
  "hu-HU": {"Noemi": "hu-HU-NoemiNeural", "Tamas": "hu-HU-TamasNeural"},
  "hy-AM": {"Anahit": "hy-AM-AnahitNeural", "Hayk": "hy-AM-HaykNeural"},
  "id-ID": {"Gadis": "id-ID-GadisNeural", "Ardi": "id-ID-ArdiNeural"},
  "is-IS": {"Gudrun": "is-IS-GudrunNeural", "Gunnar": "is-IS-GunnarNeural"},
  "it-IT": {
    "Elsa": "it-IT-ElsaNeural",
    "Isabella": "it-IT-IsabellaNeural",
    "Diego": "it-IT-DiegoNeural",
    "AlessioMultilingual": "it-IT-AlessioMultilingualNeural",
    "IsabellaMultilingual": "it-IT-IsabellaMultilingualNeural",
    "GiuseppeMultilingual": "it-IT-GiuseppeMultilingualNeural",
    "MarcelloMultilingual": "it-IT-MarcelloMultilingualNeural",
    "Benigno": "it-IT-BenignoNeural",
    "Calimero": "it-IT-CalimeroNeural",
    "Cataldo": "it-IT-CataldoNeural",
    "Fabiola": "it-IT-FabiolaNeural",
    "Fiamma": "it-IT-FiammaNeural",
    "Gianni": "it-IT-GianniNeural",
    "Giuseppe": "it-IT-GiuseppeNeural",
    "Imelda": "it-IT-ImeldaNeural",
    "Irma": "it-IT-IrmaNeural",
    "Lisandro": "it-IT-LisandroNeural",
    "Palmira": "it-IT-PalmiraNeural",
    "Pierina": "it-IT-PierinaNeural",
    "Rinaldo": "it-IT-RinaldoNeural"
  },
  "iu-CANS-CA": {
    "Siqiniq": "iu-Cans-CA-SiqiniqNeural",
    "Taqqiq": "iu-Cans-CA-TaqqiqNeural"
  },
  "iu-LATN-CA": {
    "Siqiniq": "iu-Latn-CA-SiqiniqNeural",
    "Taqqiq": "iu-Latn-CA-TaqqiqNeural"
  },
  "ja-JP": {
    "Nanami": "ja-JP-NanamiNeural",
    "Keita": "ja-JP-KeitaNeural",
    "Aoi": "ja-JP-AoiNeural",
    "Daichi": "ja-JP-DaichiNeural",
    "Mayu": "ja-JP-MayuNeural",
    "Naoki": "ja-JP-NaokiNeural",
    "Shiori": "ja-JP-ShioriNeural",
    "MasaruMultilingual": "ja-JP-MasaruMultilingualNeural",
    "Masaru:DragonHD": "ja-JP-Masaru:DragonHDLatestNeural",
    "Nanami:DragonHD": "ja-JP-Nanami:DragonHDLatestNeural"
  },
  "jv-ID": {"Siti": "jv-ID-SitiNeural", "Dimas": "jv-ID-DimasNeural"},
  "ka-GE": {"Eka": "ka-GE-EkaNeural", "Giorgi": "ka-GE-GiorgiNeural"},
  "kk-KZ": {"Aigul": "kk-KZ-AigulNeural", "Daulet": "kk-KZ-DauletNeural"},
  "km-KH": {"Sreymom": "km-KH-SreymomNeural", "Piseth": "km-KH-PisethNeural"},
  "kn-IN": {"Sapna": "kn-IN-SapnaNeural", "Gagan": "kn-IN-GaganNeural"},
  "ko-KR": {
    "SunHi": "ko-KR-SunHiNeural",
    "InJoon": "ko-KR-InJoonNeural",
    "HyunsuMultilingual": "ko-KR-HyunsuMultilingualNeural",
    "BongJin": "ko-KR-BongJinNeural",
    "GookMin": "ko-KR-GookMinNeural",
    "Hyunsu": "ko-KR-HyunsuNeural",
    "JiMin": "ko-KR-JiMinNeural",
    "SeoHyeon": "ko-KR-SeoHyeonNeural",
    "SoonBok": "ko-KR-SoonBokNeural",
    "YuJin": "ko-KR-YuJinNeural"
  },
  "lo-LA": {
    "Keomany": "lo-LA-KeomanyNeural",
    "Chanthavong": "lo-LA-ChanthavongNeural"
  },
  "lt-LT": {"Ona": "lt-LT-OnaNeural", "Leonas": "lt-LT-LeonasNeural"},
  "lv-LV": {"Everita": "lv-LV-EveritaNeural", "Nils": "lv-LV-NilsNeural"},
  "mk-MK": {
    "Marija": "mk-MK-MarijaNeural",
    "Aleksandar": "mk-MK-AleksandarNeural"
  },
  "ml-IN": {"Sobhana": "ml-IN-SobhanaNeural", "Midhun": "ml-IN-MidhunNeural"},
  "mn-MN": {"Yesui": "mn-MN-YesuiNeural", "Bataa": "mn-MN-BataaNeural"},
  "mr-IN": {"Aarohi": "mr-IN-AarohiNeural", "Manohar": "mr-IN-ManoharNeural"},
  "ms-MY": {"Yasmin": "ms-MY-YasminNeural", "Osman": "ms-MY-OsmanNeural"},
  "mt-MT": {"Grace": "mt-MT-GraceNeural", "Joseph": "mt-MT-JosephNeural"},
  "my-MM": {"Nilar": "my-MM-NilarNeural", "Thiha": "my-MM-ThihaNeural"},
  "nb-NO": {
    "Pernille": "nb-NO-PernilleNeural",
    "Finn": "nb-NO-FinnNeural",
    "Iselin": "nb-NO-IselinNeural"
  },
  "ne-NP": {"Hemkala": "ne-NP-HemkalaNeural", "Sagar": "ne-NP-SagarNeural"},
  "nl-BE": {"Dena": "nl-BE-DenaNeural", "Arnaud": "nl-BE-ArnaudNeural"},
  "nl-NL": {
    "Fenna": "nl-NL-FennaNeural",
    "Maarten": "nl-NL-MaartenNeural",
    "Colette": "nl-NL-ColetteNeural"
  },
  "or-IN": {
    "Subhasini": "or-IN-SubhasiniNeural",
    "Sukant": "or-IN-SukantNeural"
  },
  "pa-IN": {"Ojas": "pa-IN-OjasNeural", "Vaani": "pa-IN-VaaniNeural"},
  "pl-PL": {
    "Agnieszka": "pl-PL-AgnieszkaNeural",
    "Marek": "pl-PL-MarekNeural",
    "Zofia": "pl-PL-ZofiaNeural"
  },
  "ps-AF": {"Latifa": "ps-AF-LatifaNeural", "GulNawaz": "ps-AF-GulNawazNeural"},
  "pt-BR": {
    "Francisca": "pt-BR-FranciscaNeural",
    "Antonio": "pt-BR-AntonioNeural",
    "MacerioMultilingual": "pt-BR-MacerioMultilingualNeural",
    "ThalitaMultilingual": "pt-BR-ThalitaMultilingualNeural",
    "Brenda": "pt-BR-BrendaNeural",
    "Donato": "pt-BR-DonatoNeural",
    "Elza": "pt-BR-ElzaNeural",
    "Fabio": "pt-BR-FabioNeural",
    "Giovanna": "pt-BR-GiovannaNeural",
    "Humberto": "pt-BR-HumbertoNeural",
    "Julio": "pt-BR-JulioNeural",
    "Leila": "pt-BR-LeilaNeural",
    "Leticia": "pt-BR-LeticiaNeural",
    "Manuela": "pt-BR-ManuelaNeural",
    "Nicolau": "pt-BR-NicolauNeural",
    "Thalita": "pt-BR-ThalitaNeural",
    "Valerio": "pt-BR-ValerioNeural",
    "Yara": "pt-BR-YaraNeural"
  },
  "pt-PT": {
    "Raquel": "pt-PT-RaquelNeural",
    "Duarte": "pt-PT-DuarteNeural",
    "Fernanda": "pt-PT-FernandaNeural"
  },
  "ro-RO": {"Alina": "ro-RO-AlinaNeural", "Emil": "ro-RO-EmilNeural"},
  "ru-RU": {
    "Svetlana": "ru-RU-SvetlanaNeural",
    "Dmitry": "ru-RU-DmitryNeural",
    "Dariya": "ru-RU-DariyaNeural"
  },
  "si-LK": {"Thilini": "si-LK-ThiliniNeural", "Sameera": "si-LK-SameeraNeural"},
  "sk-SK": {"Viktoria": "sk-SK-ViktoriaNeural", "Lukas": "sk-SK-LukasNeural"},
  "sl-SI": {"Petra": "sl-SI-PetraNeural", "Rok": "sl-SI-RokNeural"},
  "so-SO": {"Ubax": "so-SO-UbaxNeural", "Muuse": "so-SO-MuuseNeural"},
  "sq-AL": {"Anila": "sq-AL-AnilaNeural", "Ilir": "sq-AL-IlirNeural"},
  "sr-LATN-RS": {
    "Nicholas": "sr-Latn-RS-NicholasNeural",
    "Sophie": "sr-Latn-RS-SophieNeural"
  },
  "sr-RS": {"Sophie": "sr-RS-SophieNeural", "Nicholas": "sr-RS-NicholasNeural"},
  "su-ID": {"Tuti": "su-ID-TutiNeural", "Jajang": "su-ID-JajangNeural"},
  "sv-SE": {
    "Sofie": "sv-SE-SofieNeural",
    "Mattias": "sv-SE-MattiasNeural",
    "Hillevi": "sv-SE-HilleviNeural"
  },
  "sw-KE": {"Zuri": "sw-KE-ZuriNeural", "Rafiki": "sw-KE-RafikiNeural"},
  "sw-TZ": {"Rehema": "sw-TZ-RehemaNeural", "Daudi": "sw-TZ-DaudiNeural"},
  "ta-IN": {
    "Pallavi": "ta-IN-PallaviNeural",
    "Valluvar": "ta-IN-ValluvarNeural",
    "Saranya": "ta-LK-SaranyaNeural",
    "Kumar": "ta-LK-KumarNeural",
    "Kani": "ta-MY-KaniNeural",
    "Surya": "ta-MY-SuryaNeural",
    "Venba": "ta-SG-VenbaNeural",
    "Anbu": "ta-SG-AnbuNeural"
  },
  "ta-LK": {"Saranya": "ta-LK-SaranyaNeural", "Kumar": "ta-LK-KumarNeural"},
  "ta-MY": {"Kani": "ta-MY-KaniNeural", "Surya": "ta-MY-SuryaNeural"},
  "ta-SG": {"Venba": "ta-SG-VenbaNeural", "Anbu": "ta-SG-AnbuNeural"},
  "te-IN": {"Shruti": "te-IN-ShrutiNeural", "Mohan": "te-IN-MohanNeural"},
  "th-TH": {
    "Premwadee": "th-TH-PremwadeeNeural",
    "Niwat": "th-TH-NiwatNeural",
    "Achara": "th-TH-AcharaNeural"
  },
  "tr-TR": {"Emel": "tr-TR-EmelNeural", "Ahmet": "tr-TR-AhmetNeural"},
  "uk-UA": {"Polina": "uk-UA-PolinaNeural", "Ostap": "uk-UA-OstapNeural"},
  "ur-IN": {"Gul": "ur-IN-GulNeural", "Salman": "ur-IN-SalmanNeural"},
  "ur-PK": {"Uzma": "ur-PK-UzmaNeural", "Asad": "ur-PK-AsadNeural"},
  "uz-UZ": {"Madina": "uz-UZ-MadinaNeural", "Sardor": "uz-UZ-SardorNeural"},
  "vi-VN": {"HoaiMy": "vi-VN-HoaiMyNeural", "NamMinh": "vi-VN-NamMinhNeural"},
  "wuu-CN": {
    "Xiaotong": "wuu-CN-XiaotongNeural",
    "Yunzhe": "wuu-CN-YunzheNeural"
  },
  "yue-CN": {
    "XiaoMin": "yue-CN-XiaoMinNeural",
    "YunSong": "yue-CN-YunSongNeural"
  },
  "zh-CN": {
    "Xiaoxiao": "zh-CN-XiaoxiaoNeural",
    "Yunxi": "zh-CN-YunxiNeural",
    "Yunjian": "zh-CN-YunjianNeural",
    "Xiaoyi": "zh-CN-XiaoyiNeural",
    "Yunyang": "zh-CN-YunyangNeural",
    "Xiaochen": "zh-CN-XiaochenNeural",
    "XiaochenMultilingual": "zh-CN-XiaochenMultilingualNeural",
    "Xiaohan": "zh-CN-XiaohanNeural",
    "Xiaomeng": "zh-CN-XiaomengNeural",
    "Xiaomo": "zh-CN-XiaomoNeural",
    "Xiaoqiu": "zh-CN-XiaoqiuNeural",
    "Xiaorou": "zh-CN-XiaorouNeural",
    "Xiaorui": "zh-CN-XiaoruiNeural",
    "Xiaoshuang": "zh-CN-XiaoshuangNeural",
    "XiaoxiaoDialects": "zh-CN-XiaoxiaoDialectsNeural",
    "XiaoxiaoMultilingual": "zh-CN-XiaoxiaoMultilingualNeural",
    "Xiaoyan": "zh-CN-XiaoyanNeural",
    "Xiaoyou": "zh-CN-XiaoyouNeural",
    "XiaoyuMultilingual": "zh-CN-XiaoyuMultilingualNeural",
    "Xiaozhen": "zh-CN-XiaozhenNeural",
    "Yunfeng": "zh-CN-YunfengNeural",
    "Yunhao": "zh-CN-YunhaoNeural",
    "Yunjie": "zh-CN-YunjieNeural",
    "Yunxia": "zh-CN-YunxiaNeural",
    "Yunye": "zh-CN-YunyeNeural",
    "YunyiMultilingual": "zh-CN-YunyiMultilingualNeural",
    "Yunze": "zh-CN-YunzeNeural",
    "Xiaochen:DragonHDFlash": "zh-CN-Xiaochen:DragonHDFlashLatestNeural",
    "Xiaoxiao:DragonHDFlash": "zh-CN-Xiaoxiao:DragonHDFlashLatestNeural",
    "Xiaoxiao2:DragonHDFlash": "zh-CN-Xiaoxiao2:DragonHDFlashLatestNeural",
    "YunfanMultilingual": "zh-CN-YunfanMultilingualNeural",
    "Yunxiao:DragonHDFlash": "zh-CN-Yunxiao:DragonHDFlashLatestNeural",
    "YunxiaoMultilingual": "zh-CN-YunxiaoMultilingualNeural",
    "Yunyi:DragonHDFlash": "zh-CN-Yunyi:DragonHDFlashLatestNeural",
    "Xiaochen:DragonHD": "zh-CN-Xiaochen:DragonHDLatestNeural",
    "Yunfan:DragonHD": "zh-CN-Yunfan:DragonHDLatestNeural"
  },
  "zh-CN-GUANGXI": {"Yunqi": "zh-CN-guangxi-YunqiNeural"},
  "zh-CN-henan": {"Yundeng": "zh-CN-henan-YundengNeural"},
  "zh-CN-liaoning": {
    "Xiaobei": "zh-CN-liaoning-XiaobeiNeural",
    "Yunbiao": "zh-CN-liaoning-YunbiaoNeural"
  },
  "zh-CN-shaanxi": {"Xiaoni": "zh-CN-shaanxi-XiaoniNeural"},
  "zh-CN-shandong": {"Yunxiang": "zh-CN-shandong-YunxiangNeural"},
  "zh-CN-sichuan": {"Yunxi": "zh-CN-sichuan-YunxiNeural"},
  "zh-HK": {
    "HiuMaan": "zh-HK-HiuMaanNeural",
    "WanLung": "zh-HK-WanLungNeural",
    "HiuGaai": "zh-HK-HiuGaaiNeural"
  },
  "zh-TW": {
    "HsiaoChen": "zh-TW-HsiaoChenNeural",
    "YunJhe": "zh-TW-YunJheNeural",
    "HsiaoYu": "zh-TW-HsiaoYuNeural"
  },
  "zu-ZA": {"Thando": "zu-ZA-ThandoNeural", "Themba": "zu-ZA-ThembaNeural"}
};
